name: WordPress Coding Standards

on:
  pull_request:
    branches:
      - master

jobs:
  wpcs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Install WPCS
        run: composer global require "wp-coding-standards/wpcs:*"

      - name: Set up WPCS
        run: |
          phpcs --config-set installed_paths ~/.composer/vendor/wp-coding-standards/wpcs
          phpcs --config-set default_standard WordPress

      - name: Run WPCS
        id: wpcs-check
        run: phpcs --standard=WordPress .

      - name: Report WPCS status
        if: ${{ always() }}
        run: |
          if [[ ${GITHUB_REF} = "refs/pull/${{ github.event.pull_request.number }}/merge" ]]; then
            if [[ ${{ steps.wpcs-check.outcome }} == 'failure' ]]; then
              echo "::set-output name=conclusion::failure"
              echo "::set-output name=details::WPCS check failed. Please fix the coding standards violations."
            else
              echo "::set-output name=conclusion::success"
              echo "::set-output name=details::WPCS check passed. The coding standards are met."
            fi
            gh pr check "${GITHUB_SHA}" --status "completed" --conclusion ${{ steps.wpcs-check.outputs.conclusion }} --name "WPCS Check" --details-url "${{ github.server_url }}/owner/repo/actions/runs/${{ github.run_id }}" --external-id "wpcs-check"
          fi
